### ISSUE TITLE
Is the v8.0.100 release built for FreeBSD 13?

### ISSUE THREAD

**Issue by nkosi23** [Thefrank/dotnet-freebsd-crossbuild#7]
Hello! :smiley: 

The readme reads:

>Currently published here: Version <= 8.0.0 FreeBSD 12.4. Version >= 8.0.1 FreeBSD 13.2

While the notes of the 8.0.1 release mention:

>This marks the last version built for FreeBSD 12

So I am confused and wonder if there are binaries available for FreeBSD 13

**Comment by Thefrank** [comment]
The 8.0.100 should work under FreeBSD 13.2 but was built under 12.4. I should clarify that!
Going forward (actually building right now) net6, net7, and net8 will target FreeBSD 13.2. I will also need to find a way of creating ABI specific nuget feeds.

**Comment by Thefrank** [comment]
@nkosi23 I clarified that it is the SDK version (compared to the runtime version)

Also. the 8.0.101 SDK should be up. It was built for FreeBSD 13.2.
